---
AWSTemplateFormatVersion: "2010-09-09"

Description:
  Creates the serverless backend using lambda, dynamodb and API Gateway

Parameters:
  NamePrefix:
    Type: String
    Default: dev
    Description: String for prefixing resources to differentiate prod/dev

Resources:

  DynamoDBTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
    #######################
    #Attributes that will be a part of the dynamodb table
    #Note you only need to define primary key attributes
    #As all other attributes added to the table do
    #not need to be defined when the table is created
    ##########################
      AttributeDefinitions:
        -
          AttributeName: "id"
          AttributeType: "S"
        -
          AttributeName: "load_id"
          AttributeType: "N"

      #on demand billing option
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        -
          AttributeName: "id"
          KeyType: "HASH"
        -
          AttributeName: "load_id"
          KeyType: "RANGE"

      #Name of the dynamodb table will be concatenated
      #with the NamePrefix paramter and string "sneakpeek-table"
      TableName:
          Fn::Join:
              - ""
              - - !Ref NamePrefix
                - "-sneakpeek-table"

Outputs:
##################################
#Provides the arn for the dynamodb table
#
##################################
  TableArn:
    Value: !GetAtt DynamoDBTable.Arn
