---
AWSTemplateFormatVersion: "2010-09-09"

Description:
  Creates the serverless backend using lambda, dynamodb and API Gateway

Parameters:
  NamePrefix:
    Type: String
    Default: dev
    Description: String for prefixing resources to differentiate prod/dev

Resources:

    DynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeDefinition
      BillingMode: String
      GlobalSecondaryIndexes:
        - GlobalSecondaryIndex
      KeySchema:
        - KeySchema
      LocalSecondaryIndexes:
        - LocalSecondaryIndex
      PointInTimeRecoverySpecification:
        PointInTimeRecoverySpecification
      ProvisionedThroughput:
        ProvisionedThroughput
      SSESpecification:
        SSESpecification
      StreamSpecification:
        StreamSpecification
      TableName: String
      Tags:
        - Tag
      TimeToLiveSpecification:
        TimeToLiveSpecification

  WebsiteBucket:
    Properties:
      BucketName: !Ref BucketName
      WebsiteConfiguration:
        IndexDocument: index.html
    Type: "AWS::S3::Bucket"

Outputs:
  WebsiteURL:
    Value: !GetAtt WebsiteBucket.WebsiteURL
