---
AWSTemplateFormatVersion: "2010-09-09"

Description:
  Creates the serverless backend using lambda, dynamodb and API Gateway

Parameters:
  NamePrefix:
    Type: String
    Default: dev
    Description: String for prefixing resources to differentiate prod/dev

Resources:

  DynamoDBTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "id"
          AttributeType: "S"
        -
          AttributeName: "customer_id"
          AttributeType: "N"
      KeySchema:
        -
          AttributeName: "id"
          KeyType: "HASH"
        -
          AttributeName: "customer_id"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName: "dev-sneakpeek"

# Outputs:
#   WebsiteURL:
#     Value: !GetAtt WebsiteBucket.WebsiteURL
