AWSTemplateFormatVersion: "2010-09-09"
Description: Automate provisioning of CodeBuild with CodePipeline CodeCommit and CodeDeploy. **WARNING** This template creates one or more Amazon EC2 instances. You will be billed for the AWS resources used if you create a stack from this template.
Parameters:
  RepositoryBranch:
    Type: String
    Default: dev
  #Default git repository used
  GitRepo:
    Type: String
    Default: https://git-codecommit.us-east-1.amazonaws.com/v1/repos/sneakpeek
  GitRepoName:
    Type: String
    Default: sneakpeek
  TagKey:
    Type: String
    Default: Name
  TagValue:
    Type: String
    Default: CodeDeployEC2Tag

  DevBuildName:
    Type: String
    Default: dev-sneekpeek-tests
  ProdStackName:
    Type: String
    Default: prod-sneekpeek

Resources:
  ArtifactStoreBucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled
      AccessControl: BucketOwnerFullControl
      Tags:
        -
          Key: stage
          Value: dev
        -
          Key: retain
          Value: false

  DevArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: codebuild-dev-sneakpeek
      Tags:
        -
          Key: stage
          Value: dev
        -
          Key: retain
          Value: false
  #################################
  #Code Build Project that runs python
  #unit/integration tests
  #
  ###################################
  SneakPeekPythonTests:
    #Need the DevArtifactsBucket Created first before This
    #CodeBuild Project can start
    DependsOn: DevArtifactsBucket
    Type: AWS::CodeBuild::Project
    Properties:
      #Output location for the CodeBuild Project
      Artifacts:
        Type: S3
        Location: codebuild-dev-sneakpeek
        Packaging: NONE
      #Allows for git badge at top of git repo
      BadgeEnabled: true
      #Where logs are written to from code build
      LogsConfig:
          CloudWatchLogs:
              Status: ENABLED
              GroupName: codebuild-dev-sneakpeek
          S3Logs:
              Status: ENABLED
              Location: codebuild-dev-sneakpeek/buildlogs
      #Standard Linux Image environment
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Type: LINUX_CONTAINER
        Image: aws/codebuild/standard:2.0
      Name: !Ref DevBuildName
      ServiceRole: arn:aws:iam::350255258796:role/DevSneakPeekCodeBuild

      #CodeCommit Git repo used for CodeBuild
      Source:
        Type: CODECOMMIT
        Location: !Ref GitRepo
      TimeoutInMinutes: 5

  ##########################################
  #Code Pipeline Is broken down into stages
  #that occur sequentially These can be
  #the following ci/cd actions
  # Source
  # Build
  # Test
  # Deploy
  # Approval
  # Invoke
  #
  #Actions for this environment:
  #Stage 1) Source = Get source code repository
  #Stage 2) Build = Build and test a dev environment
  ###########################################
  CodePipelineStack:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RoleArn: !GetAtt [CodePipelineRole, Arn]
      ArtifactStore:
        Location:
          Ref:
            ArtifactStoreBucket
        Type: S3
      Stages:
        ###############################
        #Stage 1, gets the source control git repo
        #
        #
        ###############################
        - Name: SourceCodeRepo
          Actions:
            #The input artifact of an action must exactly
            # match the output artifact declared
            #in a preceding action
            - InputArtifacts: []
              Name: Source
              ######################################
              #List of valid action type providers
              #by action can be found here:
              #https://docs.aws.amazon.com/codepipeline/latest/userguide/reference-pipeline-structure.html#actions-valid-providers
              ######################################
              ActionTypeId:
                Category: Source
                Owner: AWS
                Version: 1
                Provider: CodeCommit
              OutputArtifacts:
                - Name: !Ref GitRepoName
            #Git repo for first stage
            #########################################
            #Configuration Details by provider can be found here:
            #https://docs.aws.amazon.com/codepipeline/latest/userguide/reference-pipeline-structure.html#structure-configuration-examples
            #
            #########################################
              Configuration:
                BranchName: !Ref RepositoryBranch
                RepositoryName: !Ref GitRepoName
              #Run order within stage not between stages
              RunOrder: 1
        ###############################
        #Stage 2 Builds the code in the
        #Dev environment
        #
        ###############################
        - Name: BuildDevEnvironment
          Actions:
          - Name: Build
              ######################################
              #List of valid action type providers
              #by action can be found here:
              #https://docs.aws.amazon.com/codepipeline/latest/userguide/reference-pipeline-structure.html#actions-valid-providers
              ######################################
            ActionTypeId:
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
            OutputArtifacts:
              - Name: BuildDev
            InputArtifacts:
              - Name: !Ref GitRepoName
            #########################################
            #Configuration Details by provider can be found here:
            #https://docs.aws.amazon.com/codepipeline/latest/userguide/reference-pipeline-structure.html#structure-configuration-examples
            #
            #########################################
            Configuration:
                ProjectName: !Ref DevBuildName
            RunOrder: 1

          ###################################
          #Stage 3) Deploys to production
          #by updating or creating a stack as
          #necessary
          ###################################
        - Name: DeployProd
          Actions:
          - Name: Deploy
            ActionTypeId:
              Category: Deploy
              Owner: AWS
              Provider: CloudFormation
              Version: '1'
            InputArtifacts:
              - Name: BuildDev
            Configuration:
              #If the
              ActionMode: CREATE_UPDATE
              RoleArn: !GetAtt [CodePipelineRole, Arn]
              StackName: !Ref ProdStackName
              #TemplatePath: !Ref GitRepoName !Sub "TemplateSource::${ProdStackConfig}"
              #Artifact::template_file_name
              #is what the deploy stage is expecting as input for the
              #cloudformation template location
              TemplatePath: sneakpeek::templates/dev_static_webpage.yml
            RunOrder: '1'

  CodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: Allow
          Principal:
            Service: codepipeline.amazonaws.com
          Action: sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess



Outputs:
  CodeCommitURL:
    Description: CodeCommit URL
    Value:
      Fn::Join:
        - ""
        - - "https://console.aws.amazon.com/codepipeline/home?region="
          - Ref: AWS::Region
          - "#/repository/"
          - Ref: AWS::StackName
          - "/browse/HEAD/--/"
  CloneUrlSsh:
    Description: SSH command for connecting to the CodeCommit repo
    Value: !Ref GitRepo
