###############################################
#This Yaml sets up the end user authentcation pool
#using aws cognito
#
#Inspired by this git example:
#https://gist.github.com/singledigit/2c4d7232fa96d9e98a3de89cf6ebe7a5
###############################################
AWSTemplateFormatVersion: "2010-09-09"
Description: Builds end user authentication resources using AWS Cognito
Parameters:
  NamePrefix:
    Type: String
    Default: prod
    Description: String for prefixing resources to differentiate prod/dev

Resources:

  ######################################
  #Cognito User pools are used for authentication
  #You are who you say you are
  #####################################
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: SneakPeek
      ###############
      #Allowable attributes for the user pool:
      #valid values are phone_number, email, or preferred_username
      #Basically what the user is allowed to login with
      ###############
      AliasAttributes:
        - email
      #How the user verify their account
      AutoVerifiedAttributes:
        - email
  ####################################
  #Will be used by our web client (static javascript calling
  #lambda functions to authenticate users)
  #
  #
  ####################################
  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: SneakPeekWeb
      UserPoolId: !Ref UserPool
      GenerateSecret: false


  ######################################
  #Cognito identity pools are used for authorization
  #you are allowed to do actions x,y,z
  # In a practical sense this is used for
  # granting a role to the client so that
  #short term privleges can be granted
  #####################################
  IdentityPool:
    Type: "AWS::Cognito::IdentityPool"
    Properties:
      IdentityPoolName:
        Fn::Join:
            - ""
            - - !Ref NamePrefix
              - "-identity-pool"
      AllowUnauthenticatedIdentities: true
      CognitoIdentityProviders:
        - ClientId: !Ref UserPoolClient
          ProviderName: !GetAtt UserPool.ProviderName


# Create a role for unauthorized acces to AWS resources. Very limited access. Only allows users in the previously created Identity Pool
  CognitoUnAuthorizedRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Federated: "cognito-identity.amazonaws.com"
            Action:
              - "sts:AssumeRoleWithWebIdentity"
            Condition:
              StringEquals:
                "cognito-identity.amazonaws.com:aud": !Ref IdentityPool
              "ForAnyValue:StringLike":
                "cognito-identity.amazonaws.com:amr": unauthenticated
      Policies:
        - PolicyName: "CognitoUnauthorizedPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "mobileanalytics:PutEvents"
                  - "cognito-sync:*"
                Resource: "*"

  #######################################################
  # Create a role for authorized acces to AWS resources.
  # Only allows users that have signed in
  #with the IdentityPool
  #
  ######################################################
  CognitoAuthorizedRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Federated: "cognito-identity.amazonaws.com"
            Action:
              - "sts:AssumeRoleWithWebIdentity"
            Condition:
              StringEquals:
                "cognito-identity.amazonaws.com:aud": !Ref IdentityPool
              "ForAnyValue:StringLike":
                "cognito-identity.amazonaws.com:amr": authenticated
      Policies:
        - PolicyName: "CognitoAuthorizedPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "mobileanalytics:PutEvents"
                  - "cognito-sync:*"
                  - "cognito-identity:*"
                Resource: "*"
              - Effect: "Allow"
                Action:
                  - "lambda:InvokeFunction"
                Resource: "*"





Outputs:
      UserPoolClientId:
        Description: Client ID used by webpage to connect to cognito
        Value: !Ref UserPoolClient

      UserPoolId:
        Description: Amazon Cognito User Pool ID
        Value: !Ref UserPool
